apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  AWS_ACCESS_KEY_ID: "QVNJQTVGNFBOTlU0QVFCM0lRRVU="
  AWS_SECRET_ACCESS_KEY: "MjlMYjV4YkNMOGExQ1RySTlMV2ptejhMTXNLMWJMaThLNlRaZlJSRg=="
  AWS_SESSION_TOKEN: "RndvR1pYSXZZWGR6RUNRYURNK1ByVmhGeVJpdjE4ZUhaU0xWQVNRK3I4bWNDVzltZDdaNCtQbmFhRnl5SDVYVXc3SWZ5VXJxaWxCbG5QVWVpWVBGZ2RTZ0RsbzdvRkRRaEVvU1hYSEtYYU1sTHQyRUluY09uMEI4QUhEVDVjUFdSQVg1N2ZMTjQ1SU52V2lNSjN5amRmNGRLVWhrTXpQMVZFWS9SengvOUovWXhtV1J5NG5xM2dRSnY0R1dCdXJKUnNyOXI4akdJMVpWOGZWZFhJWktmOXBBeHh3K0hrUnlkSHJTbXkxN3NmR21XbVh4bWVPTjI3NFNrYTcyZ0xNTnVHdFpDakV6ekdsRGozQ01FOHdZa1hIdDcwWWVURDZvZGdnL0FYQnJkLzM1Mmd6L3ZXZzNobW9vTDB3QUM0ZDdQQ2k0ajgycUJqSXRzelRhMU02Q3BvRU01T3FicVVZaGdqWmhUbHhkN3NoMTRhSVdCUDlzaUtJOEVUL1pDb1lOSTNiQUhLM2k="